'use strict';

module.exports = {
  'always-semicolon': true,

  'block-indent': '  ',

  'space-before-colon': '',
  'space-after-colon': ' ',

  'space-before-selector': '\n\n',
  'space-before-opening-brace': ' ',
  'space-after-opening-brace': '\n',
  'space-between-declarations': '\n',
  'space-before-closing-brace': '\n',

  'sort-order': [
    [
      'composes',
    ],
    [
      'position',
      'z-index',
      'top',
      'right',
      'bottom',
      'left',
    ],
    [
      'display',
      'visibility',
      'float',
      'clear',
      'overflow',
      'overflow-x',
      'overflow-y',
    ],
    [
      'columns',
      'column-width',
      'column-count',
      'flex-flow',
      'flex-direction',
      'flex-wrap',
      'justify-content',
      'align-items',
      'align-content',
    ],
    [
      'order',
      'flex',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'align-self',
    ],
    [
      'box-sizing',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
    ],
    [
      'font',
      'font-style',
      'font-variant',
      'font-weight',
      'font-stretch',
      'font-size',
      'line-height',
      'font-family',
    ],
    [
      'content',
      'cursor',
      'user-select',
      'transition',
      'transition-property',
      'transition-duration',
      'transition-timing-function',
      'transition-delay',
      'transform',
      'transform-origin',
      'transform-style',
      'animation',
      'text-align',
      'text-decoration',
      'white-space',
    ],
    [
      'opacity',
      'border',
      'border-width',
      'border-style',
      'border-color',
      'border-top-width',
      'border-top-style',
      'border-top-color',
      'border-right',
      'border-right-width',
      'border-right-style',
      'border-right-color',
      'border-bottom',
      'border-bottom-width',
      'border-bottom-style',
      'border-bottom-color',
      'border-left',
      'border-left-width',
      'border-left-style',
      'border-left-color',
      'border-radius',
      'border-top-left-radius',
      'border-top-right-radius',
      'border-bottom-right-radius',
      'border-bottom-left-radius',
      'background',
      'background-image',
      'background-position',
      'background-position-x',
      'background-position-y',
      'background-size',
      'background-repeat',
      'background-attachment',
      'background-origin',
      'background-clip',
      'background-blend-mode',
      'background-color',
      'color',
      'outline',
      'outline-color',
      'outline-style',
      'outline-width',
      'box-shadow',
      'text-shadow',
    ],
  ],
};
